const { address, image, internet, name, random, lorem } = require('faker')

console.log('address')
console.log(address.streetAddress())
console.log(address.city())
console.log(address.stateAbbr())
console.log(address.zipCode())
console.log('internet')
console.log(internet.email())
console.log('name')
console.log(name.firstName())
console.log(name.lastName())
console.log('image')
console.log(image.imageUrl())
console.log(image.people())
console.log(image.city())
console.log(random.number({ min: 0, max: 4 }))
console.log(random.words())
console.log(lorem.paragraph())
